services:
  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end-task5
    container_name: softy-pinko-back-end-task5

  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end-task5
    container_name: softy-pinko-front-end-task5
    depends_on:
      - backend

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy-task5
    container_name: softy-pinko-proxy-task5
    ports:
      - "80:80"
    depends_on:
      - frontend

